---
- name: Login to docker registries
  docker_login: "{{ item }}"
  loop: "{{ docker_logins }}"

- name: Execute docker-compose tasks
  include_tasks:
    file: run-docker-compose.yml
    apply:
      become: "{{ 'yes' if docker_compose_item.docker_user is defined else 'no' }}"
      become_user: "{{ docker_compose_item.docker_user | default(omit) }}"
      become_flags: "{{ '-H' if docker_compose_item.docker_user is defined else omit }}"
  loop: "{{ docker_compose_setups }}"
  loop_control:
    loop_var: docker_compose_item


- name: Logout from docker registries
  docker_login: "{{ item | combine({'state': 'absent'}) }}"
  loop: "{{ docker_logins }}"
